"""add cascade delete to training foreign key

Revision ID: 16e41b50548d
Revises: 2550bf2676dd
Create Date: 2026-04-18 13:55:49.854217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e41b50548d'
down_revision = '2550bf2676dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('trainings_model_config_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'model_configs', ['model_config_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trainings_model_config_id_fkey'), 'model_configs', ['model_config_id'], ['id'])

    # ### end Alembic commands ###
