"""buat db

Revision ID: 2550bf2676dd
Revises: 3faf22adea1c
Create Date: 2026-04-13 00:24:57.684150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2550bf2676dd'
down_revision = '3faf22adea1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('idioms_idiom_text_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('idioms_idiom_text_key'), ['idiom_text'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
