"""add status and progress to preprocessing

Revision ID: 3faf22adea1c
Revises: 8062b26f8a8f
Create Date: 2026-04-10 23:16:20.905941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faf22adea1c'
down_revision = '8062b26f8a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessings', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
