"""add metrics column to testings

Revision ID: 529c7dad61fb
Revises: 91a6ad4ffa59
Create Date: 2026-04-30 02:27:07.279716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '529c7dad61fb'
down_revision = '91a6ad4ffa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testings', schema=None) as batch_op:
        batch_op.drop_column('metrics')

    # ### end Alembic commands ###
