"""make idiom_text unique and store lowercase

Revision ID: 631016e85596
Revises: f7e590d4c8a7
Create Date: 2026-04-07 20:41:00.123801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631016e85596'
down_revision = 'f7e590d4c8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['idiom_text'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
