"""add model_config table

Revision ID: 6c0f10e0cfa3
Revises: 631016e85596
Create Date: 2026-04-09 23:06:24.281209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c0f10e0cfa3'
down_revision = '631016e85596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint(batch_op.f('model_configs_train_dataset_id_fkey'), type_='foreignkey')
        batch_op.drop_column('train_dataset_id')
        batch_op.drop_column('parameters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('train_dataset_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('model_configs_train_dataset_id_fkey'), 'datasets', ['train_dataset_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('params')

    # ### end Alembic commands ###
