"""add training table

Revision ID: 8062b26f8a8f
Revises: 6c0f10e0cfa3
Create Date: 2026-04-09 23:38:18.309612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8062b26f8a8f'
down_revision = '6c0f10e0cfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('model_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('confusion_matrix')
        batch_op.drop_column('f1_score')
        batch_op.drop_column('fold_info')
        batch_op.drop_column('recall')
        batch_op.drop_column('accuracy')
        batch_op.drop_column('trained_at')
        batch_op.drop_column('epoch')
        batch_op.drop_column('precision')
        batch_op.drop_column('best_model_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_model_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('epoch', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('trained_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fold_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('f1_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confusion_matrix', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('model_path')
        batch_op.drop_column('metrics')
        batch_op.drop_column('progress')
        batch_op.drop_column('status')
        batch_op.drop_column('dataset_filename')

    # ### end Alembic commands ###
