"""add name to preprocessing

Revision ID: 808e5cd7f39e
Revises: 16e41b50548d
Create Date: 2026-04-24 12:35:48.721034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808e5cd7f39e'
down_revision = '16e41b50548d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessings', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
