"""add status and progress to testings

Revision ID: ae788a8ab7df
Revises: 808e5cd7f39e
Create Date: 2026-04-26 18:43:14.221713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae788a8ab7df'
down_revision = '808e5cd7f39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.alter_column('test_dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testings', schema=None) as batch_op:
        batch_op.alter_column('test_dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('progress')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
