"""Add emotion column to idioms

Revision ID: bf3990d730a8
Revises: 2f7d005e6fd4
Create Date: 2026-05-03 20:41:25.791067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3990d730a8'
down_revision = '2f7d005e6fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.drop_column('emotion')

    # ### end Alembic commands ###
