"""drop unique constraint on idiom_text

Revision ID: f7e590d4c8a7
Revises: 314ba2785f67
Create Date: 2026-04-07 17:01:38.818368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e590d4c8a7'
down_revision = '314ba2785f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('idioms_idiom_text_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('idioms_idiom_text_key'), ['idiom_text'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
